---
- name: Close an issue
  community.general.jira:
    uri: "{{ jira_server }}"
    username: "{{ jira_username }}"
    password: "{{ jira_token }}"
    project: "{{ jira_project }}"
    validate_certs: false
    issue: "{{ jira_issue_id }}" 
    operation: transition
    status: Close Issue