namespace: rsoliman
name: jira_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo Jira Service Desk automation using Ansible.

license:
- "MIT"

tags: ['Jira','servicedesk','demo','ansible','raedrizk','rsoliman']

dependencies:
    "community.general": "*"
    "ansible.builtin": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
